# aka.ms/yaml
resources:
  repositories:
    - repository: powercd
      type: github
      name: JustinGrote/PowerCD
      endpoint: github
      #ref: refs/heads/ci # optional ref to pin to


trigger:
  branches:
    include:
      - master
      - production
      - ci

stages:
- template: .ci/PowerCD.yml@powercd
  parameters:
    vmImage:
      - 'ubuntu-latest'
      - 'windows-latest'
      - 'macOS-latest'
    psVersion:
      - pwsh
      - powershell
    script: './build.ps1'
    linuxContainer: 'skip'
    windowsContainer: 'skip'