# Repo: Contoso/WindowsProduct
# File: azure-pipelines.yml
resources:
  repositories:
    - repository: powercd
      type: github
      name: JustinGrote/PowerCD
      ref: refs/tags/v0.8.0 # optional ref to pin to
      endpoint: github

trigger:
  branches:
    include:
      - master
      - production
      - ci

stages:
- stage: build
  displayName: Build Powershell Module
  jobs:
  - template: .ci/PowerCD.yml@powercd
    parameters:
      vmImage:
        - 'ubuntu-latest'
        - 'windows-latest'
        - 'macOS-latest'
      psVersion:
        - pwsh
        - powershell
      script: '$verbosepreference='continue';$debugpreference='continue';./build.ps1 -verbose'
      linuxContainer: 'skip'
      windowsContainer: 'skip'